# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fatos CN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fatos CN
	pod 'Alamofire'

  target 'Fatos CNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
